repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      - id: ruff
        name: ruff linter
        args: [--fix]
        exclude: ^(handler\.py|test_handler\.py|patch_weights_only\.py)$
      - id: ruff-format
        name: ruff formatter
        exclude: ^(handler\.py|test_handler\.py|patch_weights_only\.py)$
      - id: ruff
        name: ruff sorter
        args: [--select, I, --fix]
        exclude: ^(handler\.py|test_handler\.py|patch_weights_only\.py)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
